# $schema: https://json.schemastore.org/dependabot-2.0.json

version: 2
updates:
  - package-ecosystem: 'pip'
    # we only want security updates from dependabot, so we set the limit to 0
    # for regular updates. See documentation for further information here:
    # https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#open-pull-requests-limit-
    open-pull-requests-limit: 0
    directory: '.'
    schedule:
      interval: 'daily'
    reviewers:
      - 'flagsmith/flagsmith-back-end'
    commit-message:
      prefix: 'deps'
