name: Pull Request

on:
  pull_request:

jobs:
  conventional-commit:
    name: Conventional Commit
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check PR Conventional Commit title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: | # mirrors changelog-sections in the /release-please-config.json
            feat
            fix
            ci
            docs
            deps
            refactor
            test
            chore
